apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mongo-authx
  template:
    metadata:
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/role: "authx-role"
      #   vault.hashicorp.com/agent-inject-dev-identi-authx-db: "dev/identi-authx-db"
      #   vault.hashicorp.com/agent-inject-template-dev-identi-authx-db: |
      #     {{- with secret "dev/identi-authx-db" -}}
      #     export MONGO_INITDB_ROOT_USERNAME={{ .Data.ROOT_USERNAME }}
      #     export MONGO_INITDB_ROOT_PASSWORD={{ .Data.ROOT_PASSWORD }}
      #     {{- end -}}
      labels:
        app: mongo-authx
    spec:
      serviceAccountName: identi-authx
      containers:
      - image: mongo:5
        name: mongo-authx
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "localdev"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "localdev"

        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-authx
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo-authx
