apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mongo-authx
  template:
    metadata:
      labels:
        app: mongo-authx
    spec:
      containers:
      - image: mongo:5
        name: mongo-authx
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "localdev"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "localdev"

        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-authx
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo-authx
